version: '3'
services:
  rabbitmq:
    image: "rabbitmq:3.6.9-management-alpine"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

#  messaging-proxy:
#    image: "messaging-proxy:latest"
#    container_name: messaging-proxy
#    environment:
#      RABBITMQ_HOST: "rabbitmq"
#      RABBITMQ_USER: "guest"
#      RABBITMQ_PASSWORD: "guest"
#    links:
#        - rabbitmq
#    ports:
#      - "8080:8080"
#    labels:
#      NAME: "messaging-proxy"
#    depends_on:
#        - rabbitmq